name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: Agent-1

    steps:
    # Step 1: Check out the repository source code
    - name: Checkout repository
      uses: actions/checkout@v4

    # Step 2: Set up the Java JDK and configure Maven caching
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin' # Popular open-source OpenJDK distribution
        cache: 'maven'          # Automatically caches your ~/.m2/repository

    # Step 3: Run the Maven command
    - name: Build and install with Maven
      run: mvn --batch-mode --update-snapshots install

    - name: Package with Maven
      run: mvn clean package

  scan:
    name: gitleaks
    runs-on: Agent-1
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: gitleaks/gitleaks-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
